FROM ubuntu:24.04

# Add Default Users
RUN useradd -m -s /bin/bash jmartinez
RUN useradd -m -s /bin/bash dbrown
RUN useradd -m -s /bin/bash ogarcia
RUN useradd -m -s /bin/bash arodriguez
RUN echo "jmartinez:password123" | chpasswd
RUN echo "dbrown:wAWSD@ASw2" | chpasswd
RUN echo "ogarcia:#T9aujf8h33" | chpasswd
RUN echo "arodriguez:asucj783E@#" | chpasswd

# Add Packages
RUN apt-get update -y
RUN apt-get install -y \ 
                    net-tools \
                    iputils-ping \
                    iproute2 \
                    dnsutils \ 
                    cron \
                    vim-tiny \
                    at \ 
                    curl \
                    lshw \
                    sudo \
                    file \
                    ncat
